export type MuseumGalleryId = "history" | "reform" | "letters" | "stage" | "studio";

export type MuseumGallery = {
  id: MuseumGalleryId;
  title: string;
  shortTitle: string;
  symbol: string;
  description: string;
};

export type MasterpieceChallenge = {
  id: string;
  galleryId: MuseumGalleryId;
  workTitle: string;
  dateLabel: string;
  objectLabel: string;
  clueTitle: string;
  evidence: [string, string, string];
  correctPlaque: string;
  distractorPlaques: [string, string];
  rationale: string;
  source: string;
  sourceUrl: string;
};

export const museumGalleries: MuseumGallery[] = [
  { id: "history", title: "Historical Study", shortTitle: "History", symbol: "⌘", description: "Annotations and evidence that re-examine the Filipino past" },
  { id: "reform", title: "Reform Essay", shortTitle: "Reform", symbol: "✦", description: "Arguments about society, dignity, education, and nationhood" },
  { id: "letters", title: "Letters & Language", shortTitle: "Letters", symbol: "✉", description: "Correspondence, translation, language, and civic instruction" },
  { id: "stage", title: "Poetry & Drama", shortTitle: "Stage", symbol: "❧", description: "Poems and plays that carry memory, longing, and civic ideals" },
  { id: "studio", title: "Artist’s Studio", shortTitle: "Studio", symbol: "◈", description: "Sculpture, portraiture, drawing, and Rizal’s wider creative practice" },
];

const moduleSource = {
  source: "Instructor-provided Module 7: Rizal’s Essays, Letters, Annotations, and Other Literary Works",
  sourceUrl: "",
};
const indolenceSource = {
  source: "Project Gutenberg: The Indolence of the Filipino",
  sourceUrl: "https://www.gutenberg.org/ebooks/6885",
};
const centurySource = {
  source: "Project Gutenberg: The Philippines a Century Hence",
  sourceUrl: "https://www.gutenberg.org/ebooks/35899",
};
const malolosSource = {
  source: "Project Gutenberg: Letter to the Young Women of Malolos",
  sourceUrl: "https://www.gutenberg.org/ebooks/17116",
};
const lifeSource = {
  source: "Project Gutenberg: Lineage, Life and Labors of José Rizal",
  sourceUrl: "https://www.gutenberg.org/ebooks/6867",
};
const museumSource = {
  source: "Intramuros Administration: Museo ni Rizal",
  sourceUrl: "https://intramuros.gov.ph/mnr/",
};
const nationalMuseumSource = {
  source: "National Museum: Dr. José Rizal Hall",
  sourceUrl: "https://www.nationalmuseum.gov.ph/exhibitions/fine-arts/galley-5/",
};
const josephineSource = {
  source: "National Museum: Rizal’s Josephine Sleeping",
  sourceUrl: "https://www.nationalmuseum.gov.ph/2024/12/30/nmp-exhibits-rizals-josephine-sleeping/",
};

function exhibit(
  id: string,
  galleryId: MuseumGalleryId,
  workTitle: string,
  dateLabel: string,
  objectLabel: string,
  clueTitle: string,
  evidence: [string, string, string],
  correctPlaque: string,
  distractorPlaques: [string, string],
  rationale: string,
  basis = moduleSource,
): MasterpieceChallenge {
  return { id, galleryId, workTitle, dateLabel, objectLabel, clueTitle, evidence, correctPlaque, distractorPlaques, rationale, ...basis };
}

export const masterpieceChallenges: MasterpieceChallenge[] = [
  exhibit("M01", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "Paris edition · 1890", "Annotated history book", "The margins challenge the center", ["Antonio de Morga supplied the seventeenth-century base text.", "Rizal added notes that questioned colonial assumptions.", "The project recovered evidence of life before Spanish rule."], "Re-read colonial history from a Filipino-centered perspective.", ["Predict the exact date of Philippine independence.", "Replace historical evidence with a fictional adventure."], "Rizal used annotation to contest colonial bias and to foreground precolonial Filipino culture and achievement."),
  exhibit("M02", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "London research · 1888–1889", "Research folio", "A historian at the British Museum", ["He copied and studied an early Spanish account.", "He compared the account with other historical writings.", "His notes did not simply accept the colonial observer’s claims."], "Use comparison and annotation as tools of historical criticism.", ["Treat every old source as automatically neutral.", "Discard all Spanish-period records without reading them."], "The Morga project models critical source work: an old text is valuable, but its perspective and claims still require examination.", lifeSource),
  exhibit("M03", "history", "Sucesos de las Islas Filipinas by Antonio de Morga", "Original work · 1609", "Colonial chronicle", "The base text in the display", ["Its author was a Spanish colonial official.", "It described the islands near the start of the seventeenth century.", "Centuries later, Rizal republished it with extensive notes."], "Preserve a useful early account while identifying its colonial viewpoint.", ["Present Rizal as the original author of Sucesos.", "Classify the chronicle as one of Rizal’s poems."], "Morga wrote the base chronicle; Rizal’s later edition transformed how Filipino readers could interrogate it.", indolenceSource),
  exhibit("M04", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "Published · 1890", "Printer’s proof with notes", "Evidence before conquest", ["The annotations point to established communities and customs.", "They challenge the claim that civilization began only with colonization.", "They connect historical knowledge with national dignity."], "Demonstrate that precolonial Filipinos possessed culture and civilization.", ["Argue that the Philippines had no history before Spain.", "Prove that every detail in Morga must be rejected."], "A central purpose of the annotations was to counter degrading colonial misconceptions about the Filipino past."),
  exhibit("M05", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "Historical scholarship", "Comparative source cards", "Two voices, one display case", ["Morga observed through the position of a colonial official.", "Rizal answered through a Filipino reformist and scholar’s perspective.", "Reading them together reveals both evidence and bias."], "Compare viewpoints instead of confusing source with unquestionable fact.", ["Choose the older author as correct in every disagreement.", "Ignore an author’s position when reading historical claims."], "The module asks students to compare Rizal and Morga because perspective shapes historical interpretation."),
  exhibit("M06", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "National consciousness", "Museum wall map", "The past becomes civic memory", ["The work looks backward to life before conquest.", "That recovery strengthened pride in Filipino heritage.", "Knowledge of the past helped readers imagine a nation."], "Connect historical consciousness with the growth of nationalism.", ["Use history only to memorize colonial officials.", "Separate national identity completely from shared memory."], "Recovering an obscured past gave Filipino readers grounds for dignity and a common historical identity."),
  exhibit("M07", "history", "Rizal’s annotations on Morga", "Critical edition", "Magnifying glass and marginalia", "What annotation can do", ["A note can correct, question, or expand a passage.", "Rizal placed a Filipino response beside a colonial account.", "The original text remained visible for comparison."], "Make historical disagreement visible beside the source being examined.", ["Hide the original text so readers cannot compare it.", "Turn every note into an unrelated personal diary entry."], "Annotation let Rizal converse critically with Morga’s text while allowing readers to see the point under dispute."),
  exhibit("M08", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "Research and publication", "Archive-to-press timeline", "From archive desk to public argument", ["The work required patient transcription and study.", "Its findings were then prepared as a published edition.", "Scholarship became available to a wider Filipino public."], "Turn archival research into an accessible intervention in public history.", ["Keep historical research private and unavailable to readers.", "Publish an edition without identifying its source text."], "The project joined archival labor with public education—a scholarly method serving national consciousness.", lifeSource),
  exhibit("M09", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "Course comparison file", "Rizal–Morga comparison panel", "Who supplied which layer?", ["The seventeenth-century narrative came first.", "The nineteenth-century notes reframed it.", "Both layers now matter to the development of Philippine historiography."], "Distinguish Morga’s chronicle from Rizal’s later critical apparatus.", ["Credit every sentence and note to Morga alone.", "Credit the original 1609 chronicle to Rizal."], "Good curation separates the base document from the later annotations while explaining why their dialogue matters."),
  exhibit("M10", "history", "Rizal’s annotated Sucesos de las Islas Filipinas", "Legacy exhibit", "Broken colonial label", "Correcting the museum label", ["A colonial label portrays Filipinos as passive and uncivilized.", "Rizal’s research supplies contrary historical evidence.", "The corrected display recognizes agency and achievement."], "Revise inherited narratives when evidence exposes their bias.", ["Preserve a harmful label because it is old.", "Replace evidence with praise that cannot be checked."], "Rizal’s historical work encourages critical inquiry: inherited narratives can and should be corrected with evidence."),

  exhibit("M11", "reform", "The Indolence of the Filipino", "La Solidaridad · 1890", "Serialized essay", "A stereotype placed on trial", ["The title examines a charge commonly made against Filipinos.", "The argument investigates historical and social causes.", "Colonial conditions—not an inborn racial flaw—are central to the analysis."], "Challenge a colonial stereotype by examining the conditions that produced it.", ["Accept indolence as a permanent biological trait.", "Offer laziness as praise for the colonial system."], "Rizal reframed the accusation of indolence as a historical problem shaped by colonial institutions and experience.", indolenceSource),
  exhibit("M12", "reform", "The Indolence of the Filipino", "Political-social essay", "Cause-and-effect diagram", "Look beyond the accusation", ["Forced labor disrupted ordinary economic life.", "Insecurity and restrictions weakened incentives.", "The essay asks readers to investigate causes before judging a people."], "Explain behavior through historical structures rather than racial prejudice.", ["Treat a stereotype as sufficient historical evidence.", "Argue that oppression always increases productive freedom."], "The essay rejects a simplistic blame narrative and traces how institutions can shape social outcomes.", indolenceSource),
  exhibit("M13", "reform", "The Indolence of the Filipino", "Critical argument", "Evidence ledger", "An argument, not an excuse", ["Rizal acknowledges a social condition worth examining.", "He disputes the colonial explanation for it.", "He connects social change with removing conditions that discourage work and progress."], "Diagnose a social problem so meaningful reform can address its causes.", ["Deny that social problems can ever exist.", "Use the essay to defend colonial abuse as necessary."], "Rizal’s method is analytical: identify a problem, test the explanation, and expose the structures that sustain it.", indolenceSource),
  exhibit("M14", "reform", "The Philippines a Century Hence", "La Solidaridad · 1889–1890", "Four-part essay", "A nation’s possible futures", ["The essay asks what continued colonial policy could produce.", "It weighs policy change, separation, and foreign intervention.", "Its future scenarios are grounded in historical and political analysis."], "Use historical trends to reason about the Philippines’ possible political future.", ["Present a supernatural prophecy with fixed dates.", "Write a travel guide to places Rizal hoped to visit."], "The essay is a political-social analysis of possible futures, not fortune-telling.", centurySource),
  exhibit("M15", "reform", "The Philippines a Century Hence", "Future-facing analysis", "Branching future map", "Policy has consequences", ["One path imagines meaningful change and equal treatment.", "Another considers the consequences of continued repression.", "The choices of colonial authorities affect the relationship’s future."], "Show that injustice can make political separation increasingly likely.", ["Claim that repression permanently guarantees loyalty.", "Argue that the future is unrelated to present policy."], "Rizal links future political outcomes to how power responds—or fails to respond—to legitimate grievances.", centurySource),
  exhibit("M16", "reform", "The Philippines a Century Hence", "National future", "Compass and horizon chart", "Agency rather than fate", ["Education and political recognition appear in the argument.", "Filipino aspirations cannot be ignored indefinitely.", "The nation’s future is shaped by people and institutions."], "Invite critical thought about self-determination, reform, and national destiny.", ["Teach that nations develop through fate alone.", "Reduce the essay to a list of European cities."], "The work encourages readers to understand the forces shaping national destiny rather than treating history as inevitable.", centurySource),
  exhibit("M17", "reform", "Articles for La Solidaridad", "Propaganda Movement", "Newspaper reading table", "Public argument enters the press", ["The periodical addressed audiences in Spain and abroad.", "Rizal wrote about Philippine conditions and civic rights.", "Print connected dispersed advocates in a shared debate."], "Use journalism to expose injustice and argue for peaceful reform.", ["Publish only private family memories.", "Avoid all discussion of Philippine public life."], "Rizal’s journalism turned social analysis into public argument within the reform movement.", museumSource),
  exhibit("M18", "reform", "Articles for La Solidaridad", "Late nineteenth century", "Printing press plate", "A pen in a movement", ["Rizal was one voice among Filipino civic advocates.", "The newspaper carried demands for rights and representation.", "Writing created debate without becoming an armed action."], "Place Rizal’s essays within a collective reform campaign.", ["Portray every issue as Rizal’s work alone.", "Classify the newspaper as a private love-letter collection."], "The Propaganda Movement was collective; curating Rizal responsibly means showing the wider network around his essays.", museumSource),
  exhibit("M19", "reform", "Rizal’s reform essays", "Course synthesis", "Theme cabinet", "Recurring ideas", ["Education develops judgment and civic capacity.", "Dignity resists degrading colonial claims.", "Historical identity strengthens national consciousness."], "Connect education, dignity, and nationhood across Rizal’s prose.", ["Reduce every essay to the same biographical trivia.", "Treat reform as unrelated to the lives of Filipinos."], "The module presents these works as a connected body of thought about reform, identity, and social responsibility."),
  exhibit("M20", "reform", "Rizal’s reform essays", "Modern relevance", "Visitor reflection label", "From reading to civic judgment", ["The essays ask readers to question easy explanations.", "They connect evidence with public responsibility.", "Their method can inform how modern claims are evaluated."], "Practice critical inquiry instead of memorizing slogans alone.", ["Accept a claim whenever it is repeated often.", "Ignore historical context when discussing modern issues."], "The lasting classroom value is not only knowing titles, but learning to test claims, evidence, and social explanations."),

  exhibit("M21", "letters", "Letter to the Young Women of Malolos", "Written · 1889", "Open civic letter", "Courage in a school campaign", ["The addressees sought permission to study Spanish.", "They challenged restrictions placed on their education.", "Rizal praised their courage and independent judgment."], "Honor women who defended their right to education and thought.", ["Warn women to avoid education and public questions.", "Celebrate obedience to every unjust restriction."], "The letter connects women’s education with courage, reason, and the future of the community.", malolosSource),
  exhibit("M22", "letters", "Letter to the Young Women of Malolos", "Tagalog letter · 1889", "Reading-room copy", "Education beyond recitation", ["The letter values understanding over blind submission.", "It asks readers to distinguish true faith from abuse of authority.", "Mothers and future generations are part of its civic vision."], "Develop informed judgment rather than passive obedience.", ["Memorize words without understanding their meaning.", "Give every authority freedom from moral criticism."], "Rizal’s praise was tied to intellectual and moral independence, not education as ornament alone.", malolosSource),
  exhibit("M23", "letters", "Letter to the Young Women of Malolos", "Women and nationhood", "School petition and reply", "A local struggle, a national lesson", ["A specific campaign for a night school prompted the letter.", "Rizal treated the women’s action as exemplary.", "Their education mattered to family and country."], "Connect women’s educational agency with national progress.", ["Treat the school campaign as unrelated to society.", "Argue that citizenship belongs only to men."], "The letter makes women active participants in reform and national development.", malolosSource),
  exhibit("M24", "letters", "Letter to the Young Women of Malolos", "Civic instruction", "Illuminated letter", "The courage to reason", ["The addressees had already taken collective action.", "The response affirms thinking for oneself.", "Moral courage matters alongside formal learning."], "Recognize education as both intellectual and ethical formation.", ["Measure learning only by the number of certificates.", "Replace judgment with unquestioning imitation."], "The letter presents educated citizenship as a union of knowledge, courage, and moral discernment.", malolosSource),
  exhibit("M25", "letters", "Correspondence with Ferdinand Blumentritt", "International exchange", "Bundle of scholarly correspondence", "Ideas travel in envelopes", ["Rizal exchanged research and political ideas with a European scholar.", "Their friendship crossed languages and borders.", "Written exchanges supported intellectual collaboration over many years."], "Use correspondence to build an international community of scholarship.", ["Treat letters only as romantic messages.", "Assume Rizal worked without intellectual partners."], "Rizal’s letters reveal the networks behind his historical, linguistic, and reform work.", lifeSource),
  exhibit("M26", "letters", "Correspondence with family members", "Across Rizal’s journeys", "Family correspondence chest", "The private voice beside the public writer", ["The messages report studies, travels, worries, and plans.", "They preserve relationships across distance.", "They reveal a more personal voice than a public essay."], "Read correspondence as evidence of both biography and historical context.", ["Assume every private letter was written for newspaper publication.", "Use letters without asking who wrote to whom or when."], "Letters are historical sources, but their audience and situation must guide interpretation.", lifeSource),
  exhibit("M27", "letters", "Translations of Hans Christian Andersen tales", "For nieces and nephews", "Illustrated translation pages", "A storyteller across languages", ["The translations were made for young family members.", "They adapt stories from another European language tradition.", "The activity displays both affection and linguistic skill."], "Use translation to share literature across language and generation.", ["Classify the pages as Rizal’s medical prescriptions.", "Present Andersen as a character invented by Rizal."], "Rizal’s Andersen translations show language learning put to a practical, family-centered literary use.", lifeSource),
  exhibit("M28", "letters", "A trilingual letter from Dapitan", "Exile correspondence", "Three-language manuscript", "One letter, three languages", ["Censors struggled to find one reader for the whole message.", "The letter moved among different languages.", "Its form demonstrated Rizal’s linguistic range."], "Use multilingual writing creatively under restrictive surveillance.", ["Prove that Rizal knew only one language.", "Classify the manuscript as an unfinished sculpture."], "The Dapitan letter is a vivid example of Rizal using linguistic versatility in an everyday act of resistance and wit.", lifeSource),
  exhibit("M29", "letters", "Rizal’s correspondence", "Historical source practice", "Envelope metadata station", "Read the postmark too", ["A letter has a sender and intended recipient.", "Its date and place shape what the message can mean.", "Private statements should not be detached from their situation."], "Interpret correspondence through audience, date, place, and purpose.", ["Read every letter as if addressed to the entire nation.", "Ignore provenance whenever a line sounds memorable."], "Responsible curation uses a letter’s context, not isolated phrases, to build historical understanding."),
  exhibit("M30", "letters", "Rizal’s letters and translations", "Course synthesis", "Language map", "Language as a bridge", ["He wrote to family, friends, and fellow scholars.", "He translated stories for younger readers.", "He moved among languages to communicate across communities."], "Treat linguistic skill as a tool for relationship, learning, and reform.", ["Reduce language study to showing off vocabulary.", "Separate communication entirely from Rizal’s public work."], "Across letters and translations, language becomes a practical bridge between people, disciplines, and countries."),

  exhibit("M31", "stage", "Mi Último Adiós", "Fort Santiago · 1896", "Farewell poem manuscript", "A poem hidden before execution", ["The poem was left untitled by its author.", "It was concealed in an alcohol stove.", "It expresses farewell, sacrifice, and love of country."], "Frame personal farewell as an offering to the homeland.", ["Celebrate a victory Rizal witnessed after 1898.", "Describe a comic scene from a school play."], "The final poem joins intimate leave-taking with a civic language of sacrifice and remembrance.", museumSource),
  exhibit("M32", "stage", "Mi Último Adiós", "Final poem · 1896", "Poem and translation panel", "Many titles, one final text", ["Rizal did not give the poem its familiar title.", "Later readers translated it into several languages.", "Andrés Bonifacio’s Tagalog version helped circulate it."], "Explain how reception and translation shaped the poem’s public afterlife.", ["Claim Rizal printed the familiar title on the manuscript.", "Treat every translation as a separate poem by Rizal."], "The work’s afterlife reminds curators to distinguish the original manuscript from later titles and translations.", museumSource),
  exhibit("M33", "stage", "A la Juventud Filipina", "Awarded · 1879", "Prize-winning ode", "Youth as the hope of the nation", ["Rizal wrote the ode while still a student.", "It received recognition from the Liceo Artístico-Literario.", "It calls on Filipino youth to cultivate talent and aspiration."], "Address the intellectual and creative potential of Filipino youth.", ["Argue that young Filipinos should avoid education.", "Write a private farewell to a European friend."], "The ode places youth, talent, and aspiration within an emerging language of nationhood.", museumSource),
  exhibit("M34", "stage", "El Consejo de los Dioses", "Awarded play · 1880", "Theater program", "The gods judge literary greatness", ["The work is a dramatic allegory rather than a novel.", "Classical deities debate the merits of famous writers.", "It earned literary recognition for the young Rizal."], "Use drama and classical allegory to examine artistic excellence.", ["Document Rizal’s eye clinic in Hong Kong.", "Annotate Morga’s colonial chronicle."], "The Council of the Gods belongs in the stage gallery because its ideas unfold through dramatic characters and debate.", museumSource),
  exhibit("M35", "stage", "Junto al Pasig", "Youthful play", "School performance script", "A drama beside the Pasig", ["Rizal composed the work during his early years as a student.", "It is a verse drama written to be spoken and performed before an audience.", "Its religious and allegorical conflict differs from his later essays."], "Recognize Rizal’s early experimentation with staged verse and allegory.", ["Classify it as a scientific species description.", "Present it as the second edition of Morga."], "Junto al Pasig shows that Rizal’s literary range included theater well before his mature reform essays.", lifeSource),
  exhibit("M36", "stage", "To the Flowers of Heidelberg", "Heidelberg · 1886", "Pressed flower and poem", "Foreign flowers carry thoughts home", ["The poem was composed during Rizal’s stay in Germany.", "Flowers become imagined messengers.", "The beauty of Heidelberg awakens longing for the Philippines."], "Transform homesickness into a lyrical connection between exile and homeland.", ["Lay out a legal plan for La Liga Filipina.", "Attack a stereotype about Filipino labor."], "The poem uses place and natural imagery to carry memory across distance.", lifeSource),
  exhibit("M37", "stage", "Hymn to Labor", "Civic poem", "Workers’ chorus sheet", "Dignity in useful work", ["The poem is organized around voices within a community.", "Labor appears as honorable and nation-building.", "Its public tone differs from an intimate love lyric."], "Celebrate productive work as a contribution to community and country.", ["Describe indolence as an inherited racial defect.", "Record a private medical diagnosis."], "The hymn places the dignity of work within a collective civic vision.", lifeSource),
  exhibit("M38", "stage", "Me Piden Versos (They Ask Me for Verses)", "Madrid · 1882", "Poetry album page", "Asked to sing far from home", ["The speaker is asked to write verses.", "Distance and memory complicate the request.", "The poem reflects an expatriate’s emotional relation to homeland."], "Express the difficulty of creating while separated from one’s country.", ["Explain a seventeenth-century colonial chronicle.", "Petition for a women’s night school in Malolos."], "The poem turns a social request for verse into reflection on displacement, memory, and artistic voice.", lifeSource),
  exhibit("M39", "stage", "Mi Retiro (My Retreat)", "Dapitan", "Poem beside a landscape sketch", "Exile as observation and reflection", ["The setting is Rizal’s life in Dapitan.", "Nature and quiet shape the poem’s atmosphere.", "The retreat is both physical place and inward reflection."], "Find meaning and creative attention within the landscape of exile.", ["Describe the publication of Noli in Berlin.", "List the votes in Rizal’s military trial."], "Mi Retiro belongs with poems that transform a specific landscape into reflection on life, solitude, and purpose.", lifeSource),
  exhibit("M40", "stage", "Rizal’s poems and plays", "Course synthesis", "Performance and reading nook", "Different forms, different effects", ["An ode addresses a public ideal through an elevated poetic voice.", "A lyric can carry homesickness, intimate memory, or a final farewell.", "A play turns ideas into characters, conflict, dialogue, and spoken action."], "Distinguish literary forms by how they communicate an idea.", ["Assume every imaginative work is a novel.", "Classify any rhymed text as historical annotation."], "Genre is not just a label: poetry and drama organize voice, audience, image, and action differently."),

  exhibit("M41", "studio", "La Venganza de la Madre (The Mother’s Revenge)", "Sculpture", "Clay sculptural group", "A mother defends her young", ["The work is visual rather than printed prose.", "Its title centers protective maternal force.", "The National Museum recognizes it as a National Cultural Treasure."], "Show Rizal’s artistic skill through a dramatic sculptural composition.", ["Classify the sculpture as a La Solidaridad article.", "Describe it as Morga’s seventeenth-century chronicle."], "Mother’s Revenge demonstrates that Rizal’s cultural production extended beyond writing into accomplished sculpture.", nationalMuseumSource),
  exhibit("M42", "studio", "Josephine Sleeping", "Dapitan · circa 1895–1896", "Small reclining sculpture", "An intimate Dapitan memento", ["The sculpture represents Josephine Bracken at rest.", "It was made during Rizal’s exile in Dapitan.", "The National Museum describes it as a personal work kept close to its maker."], "Preserve an intimate artistic record of Rizal’s final domestic chapter.", ["Treat the sculpture as an official colonial monument.", "Attribute the work to Antonio de Morga."], "Josephine Sleeping offers a small-scale, human view of Rizal as an artist and companion in Dapitan.", josephineSource),
  exhibit("M43", "studio", "Portrait of Saturnina Rizal Hidalgo", "Oil painting · circa 1878", "Oil portrait", "The elder sister on canvas", ["The sitter was Rizal’s eldest sister.", "The National Museum identifies it as a rare surviving oil portrait by Rizal.", "Rizal painted it while still young."], "Recognize portraiture as part of Rizal’s early artistic practice.", ["Present the painting as a self-portrait by Saturnina.", "Place it among Rizal’s political essays."], "The portrait documents Rizal’s skill in oil painting and his close family world before his mature political writings.", nationalMuseumSource),
  exhibit("M44", "studio", "Prometheus Bound", "Brussels · 1890", "Sculpture", "A classical figure in restraint", ["The title draws on Greek mythology.", "Museo ni Rizal lists it among Rizal’s sculptures.", "It was made during his European years."], "Connect Rizal’s studio practice with classical artistic subjects.", ["Classify the work as a letter to the women of Malolos.", "Present it as a map of Dapitan’s waterworks."], "Prometheus Bound shows Rizal using a classical subject in a visual medium during his Brussels period.", museumSource),
  exhibit("M45", "studio", "Triumph of Death over Life", "Sculpture", "Allegorical sculpture", "An idea modeled in three dimensions", ["The title stages an abstract struggle.", "The work belongs to Rizal’s sculptural output.", "Its allegorical form communicates through bodies and composition."], "Use sculpture to embody an abstract conflict between death and life.", ["Treat the title as a chapter from El Filibusterismo.", "Classify it as a family letter from Calamba."], "The sculpture makes an idea visible and spatial, showing a different expressive method from an essay or poem.", museumSource),
  exhibit("M46", "studio", "Sketch of Leonor Rivera", "Crayon portrait", "Portrait drawing", "A likeness made by hand", ["The medium is drawing rather than photography.", "The subject was personally significant to Rizal.", "Museo ni Rizal displays the sketch among examples of his visual art."], "Read a portrait sketch as both artistic practice and personal artifact.", ["Assume the image is a documentary photograph.", "Place it in the historical-annotation gallery."], "The sketch combines visual observation with personal history and should be labeled honestly as an artwork, not a photograph.", museumSource),
  exhibit("M47", "studio", "Sketch of Ferdinand Blumentritt", "Portrait drawing", "Friendship portrait", "Scholar and sitter", ["The subject was Rizal’s friend and correspondent.", "The work joins an intellectual relationship with portrait art.", "It belongs to the visual record of Rizal’s international circle."], "Connect portraiture with the network of friendship behind Rizal’s scholarship.", ["Identify Blumentritt as the author of Morga’s Sucesos.", "Present the sketch as a printed La Solidaridad editorial."], "The drawing gives visual form to a scholarly friendship also preserved through correspondence.", museumSource),
  exhibit("M48", "studio", "Self-portrait by José Rizal", "Drawing", "Artist’s self-study", "The observer observes himself", ["The maker and sitter are the same person.", "Museo ni Rizal includes a self-portrait among his artworks.", "The work reveals visual self-representation, not written autobiography."], "Distinguish an artist’s visual self-study from a biographical text.", ["Label the work as a photograph taken by Rizal.", "Classify it as a reform essay about representation."], "A self-portrait is constructed through line and observation; it is visual evidence, but not a transparent photograph of identity.", museumSource),
  exhibit("M49", "studio", "Bust of Ricardo Carnicero", "Dapitan period", "Portrait bust", "The commandant in clay", ["Ricardo Carnicero was connected with Rizal’s Dapitan exile.", "The National Museum lists his bust among Rizal’s gallery works.", "A bust concentrates on the sitter’s head and upper body."], "Document a person in Rizal’s Dapitan world through sculptural portraiture.", ["Present Carnicero as a character from Noli Me Tangere.", "Classify the bust as Rizal’s final poem."], "The bust belongs to Rizal’s visual record of people he encountered, and its Dapitan context clarifies the relationship.", nationalMuseumSource),
  exhibit("M50", "studio", "Rizal as visual artist", "Museum synthesis", "Mixed-media cabinet", "Beyond doctor and novelist", ["The gallery includes paintings, sketches, and sculpture.", "Some works portray relatives, friends, and companions.", "Others use allegory and classical subjects."], "Recognize the range of Rizal’s artistic practice without reducing him to one role.", ["Claim that Rizal produced only two novels.", "Treat every object in the cabinet as a historical text."], "The studio gallery completes a broader picture of Rizal as a polymath whose ideas and relationships also took visual form.", nationalMuseumSource),
];

export const museumGalleriesById = Object.fromEntries(
  museumGalleries.map((gallery) => [gallery.id, gallery]),
) as Record<MuseumGalleryId, MuseumGallery>;
